### ISSUE TITLE
Location object and generative algorithm for burgs

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#11]
# What

Create class for locations. Create algorithm to pick locations. Spin through all burgs and assign locations. 

### Type

- Bool: isBurgLocation
- Enum: quality
- String: type
- Enum: citySize
- int: biome
- Tag[]: goods
- Enum[]: services
- Bool: allowMultiple
- Bool: needsPort
- Bool: needsCitadel
- Bool: needsPlaza
- Bool: needsWalls
- Bool: needsShanty
- Bool: needsTemple
- Bool: needsCol
- Bool: isWild
- Enum: Size
- Enum: requiresExploring

### Location 

Two classes for Burg and Cell. They may required unique properties later

- string: name
- string: type
- Enum: quality
- int: parent (Burg or Cell ID)
- Tag[]: goods
- Enum[]: services

## Todo's 

- [x] Base Interface
- [x] Record for Location Types
- [x] List of records
- [x] Class for Location
- [x] List in Burg
- [x] Algorithm 
- [x] Apply algorithm to burgs
- [x] Fix population calculation
- [x] Add castle required locations
- [x] Add hamlet locations for cells
