### ISSUE TITLE
Exploration

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#14]
# Options to explore in home screen

Player can choose to explore an area that is not 100% explored. 

## Todo

- [x] Map `E` to explore
- [x] If in a cell explore, small cells explore 3 times, large cells 5 times
- [x] If in a location that requires exploration, number of explorations required equals enum value
