### ISSUE TITLE
Stamina

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#15]
# Party Stamina

Stamina is the amount movement a party can perform before requiring a rest.

## ToDo

- [x] Add stamina property to party
- [x] Stamina is reduced by 10% when moving to a new cell
- [x] Exploring a cell requires 5%
- [x] Moving to a burg requires 1%
- [x] Moving to a location requires .2%
- [x] Exploring a location requires .5%
- [x] If there is not enough stamina to perform an action then deny the action and display warning
- [x] Add camp option to navigation, map to `C`, restore 50% stamina no more than 100%
