### ISSUE TITLE
Location view and navigations

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#17]
# Location view and navigation

Need ability to navigate to locations

## ToDos

- [x] In navigation display Cell locations as options with `Ctrl+` in separate table below area table
- [x] In navigation when in a burg display navigation options for available locations
- [x] When at a location, Navigation should give option to leave only using `L`
- [x] When at a location, Home should populate Location details in location panel
- [x] When saving, preserve current location
