### ISSUE TITLE
Randomly earn money while exploring

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#21]
# Earn money while exploring 

In order to facilitate rewards and buying goods and services, a currency system is needed. This will be based on the DND system. Money will be randomly earned by exploring for now until the encounter system is implemented.

## Todo

- [x] Add integer money property to player object
- [x] On exploitation roll a d100 for silver earned
- [x] Add inventory list to player class
  - inventory object just needs a name and list of tags
  - tags just have a description
- [x] Alter Home Screen to show location details, party details, then player details 
  - location details needs to be a compressed version of current screen 
  - party panel should show list of members and stamina 
  - player panel should show name, inventory capacity, and money
