### ISSUE TITLE
Lodging

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#22]
# Setup Lodging service 

Now that players have to spend stamina to move and players randomly earn coin, goods and services can now be implemented. The first service to be added is lodging. This will allow players to recover stamina at various rates. Camping recovery will be further reduced to incentivize using paid lodging (camping will eventually have other risks).

To enable this feature, the game will need a dialogue system. Higher rarity lodging will give higher amounts of stamina back at higher costs. Rare and legendary will also allow stamina to be recovered beyond 100%.

## Todo's 

- [x] When a location provides lodging then open the dialogue screen
- [x] Screen should provide option for renting a room.
- [x] Room rental will have options based on rarity. Higher rarity gives more options including the lower options.
- [x] Staying at a lodging will increase stamina.
  - [x] Camping will increase to %50
  - [x] Common will increase to %75
  - [x] Uncommon will increase to %100
  - [x] Rare will increase to %125
  - [x] Epic will increase to %150
  - [x] Legendary will increase to %200
- [x] Renting a room reduces money.
- [x] Option the player can't afford should be greyed out. Selecting one of those returns an error message.

**Comment by bcolemutech** [comment]
Need to build event engine to complete this.
