### ISSUE TITLE
Preloaded maps

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#24]
# Preloaded Maps

When starting the game for the first time the game should come with maps so that the player can get started right away.

## ToDo

- [ ] Create a small test map
- [ ] When setting up config space for the first time load preload maps into `Maps` folder
- [ ] Create a large world map
