### ISSUE TITLE
Better UI flow for redirection

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#29]
## Overview

Need to improve flow between render to input so views can send a redirect back to render processing. This will bypass input handling so that the redirect can load. A new model will be needed to encapsulate both redirect options and input to keep code concise.

## Todo

- [x] `Flow` object
  - [x] Console Key 
  - [x] Redirect (Screen Enum)
- [x] Process flow object in game service
- [x] Bypass input if redirect is set
