### ISSUE TITLE
Inventory Screen

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#32]
## The Inventory Screen

The Inventory screen is a hotkey screen that is mapped to the `I` key. This screen will give a navigable display of all items in the inventory in a table view. There should be an option to discard a selected item.

## Todos

- [x] Basic screen navigated to by the `I` key
- [x] Data storage for player inventory
- [x] Add random gems or tokens to random acquirement during exploration
- [x] Display inventory on left side.
- [x] Arrow and W,S navigation through list
- [x] `D` or `Del` key to discard item
