### ISSUE TITLE
Enable selling merch to vendors

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#33]
## Enable Selling Inventory Items to stores

Now that the item screen is available and items are being collected during play, the player needs to be able to sell them. To do this when a player visits a store having the `sell` service and player selects this service, open a screen with all sellable goods. When an item is selected the enter key can be used to start a sale confirmation. Selling the item removes the item from inventory and adds coin to the player.

## Todo's 

- [x] Open filtered inventory like screen when `sell` service is selected
- [x] Screen should navigate just like the inventory screen
- [x] `L` key to go back to service selection dialogue 
- [x] Type enter to move to confirmation screen 
- [x] No, return to selling screen
- [x] Yes, remove item from inventory and add coin to player
