### ISSUE TITLE
Enable buying from vendors

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#35]
## Enable buying items from vendors

Next step for Inventory is making purchases. To do this any vendor with a `Buy` service type and `Goods` should display all available goods for the locations `Rarity`.

### Todos

- [x] Add shop items from DnD catalog
- [x] Methods to pull items based on `Goods` collection
- [x] Screen to display all available items to purchase
- [x] Add item to inventory and decrement coin
