### ISSUE TITLE
Equipment screen

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#36]
## Equipment

Players can equip certain items but only one of an item with the exception of one-handed weapons, which the player can hold two. Equipment will be indicated in the inventory screen. When equipping an item the equipped bool becomes true. if another item of the same type is equipped then the items are swapped. In the case of one-handed weapons two can be equipped and the third attempt will swap out the first of the weapons equipped. If the weapon is two handed it replaces all handed items. Equipping an item that is already equipped will unequip it.

### ToDos

- [x] Add equipped bool to item
- [x] Add equipment  enum to items
- [x] Show equipped column in inventory screen
- [x] Add equipe key option with rules based on equipment enum
