### ISSUE TITLE
Fix tag types

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#40]
## Fix Tag Types

Tag types should reflect unique aspects of the game not just the type of goods. Tag Types should indicate item types for the purpose of shop lists, true. Types should also indicate what skills the item is affected by, damage type, and special abilities.

Tag Types need to be alter to have the following:

- **Goods**: used to identify the sellable type and is cross-referenced with the shop's goods labels
- **Skills**: used to identify the skills associated with the item for character progression
- **Special**: Could be a common tag used to indicate quest items. Could also be a tag used to identify something unique about the item.

### ToDos

- [x] Alter tag types
- [x] Update LocationTypes with goods labels instead of tags
- [x] Update tag type on all items to `Goods` type
