### ISSUE TITLE
Combat Encounters

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#43]
## Combat 

Create combat encounters when exploring! The fight is on, we are armed and armored. This story will be to calculate a combat encounter when exploring. Thid will be based on a D20 roll to determine if an encounter happens and how difficult it will be. This calculation will be based on the area's challenge rating plus the dice roll. Only a roll greater than 5 will start combat. Only combat earns a reward, which will use the existing random reward.

### ToDos

- [ ] Add challenge rating to areas based on distance from City of Light
  - [ ] Calculate challenge distance based on map dimensions
  - [ ] Determine distance of area to area where City of Light is
  - [ ] Use these to calculate a challenge rating for every area where City of Light is easiest
- [ ] When exploring roll for encounter 
  - [ ] If over 5 return message with challenge rating and reward earned. 
  - [ ] If 5 or less return generic explored message do not give a reward
