### ISSUE TITLE
Open SVG with location identifier in browser

### ISSUE THREAD

**Issue by bcolemutech** [bcolemutech/dol-con-v2#5]
## What?

Need ability to visualize where the player is.

## Why?

So that players can make good judgement on navigating the world.

### Todo

- [x] Get and store SVG
- [x] Bind 'M' key to visualizing service 
- [x] Open browser with SVG
- [x] Get image for identifier 
- [x] identify location on SVG for identifier 
- [x] Add identifier to SVG image

**Comment by bcolemutech** [comment]
Need to update SVG when moving between cells. Only open SVG when pressing M. Need to fix direction calc too.
